name: kubernetes_deployment
on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
 
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
 
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
 
    - name: Setup kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-fargate-cluster --region us-east-1
 
    - name: Deploy Appointment Service
      run: |
        kubectl apply -f app/appointment-service/appointment-deployment.yml --validate=false
        kubectl apply -f app/appointment-service/appointment-service.yml --validate=false
 
    - name: Deploy Patient Service
      run: |
        kubectl apply -f app/patient-service/patient-deployment.yml --validate=false
        kubectl apply -f app/patient-service/patient-service.yml --validate=false
 
    - name: Apply Shared Ingress
      run: |
        kubectl apply -f ingress.yml --validate=false
